config/routes.rb
Rails.application.routes.draw do
  resources :dogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#index"

  get '/twilio-test', to: "pages#test"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/api/v1/dogs_controller.rb
class Api::V1::DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  def index
    @dogs = Dog.all.order(name: :asc)
    render json: @dogs
  end

  def show
    if @dog
      render json: @dog
    else
      render json: @dog.errors
    end
  end

  def new
    @dog = dog.new
  end

  def edit
  end

  def create
    @dog = dog.new(dog_params)

    if @dog.save
      render json: @dog
    else
      render json: @dog.errors
    end
  end

  def update
  end

  def destroy
    @dog.destroy

    render json: { notice: 'dog was successfully removed.' }
  end

  private

    def set_dog
      @dog = dog.find(params[:id])
    end

    def dog_params
      params.require(:dog).permit(:name, :sex, :breed, :current_weight, :birthdate, :age)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: %i[ show edit update destroy ]

  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
    render :show
  end

  def new
    @dog = Dog.new
  end

  def edit
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.is_metric = params[:units] == "kilograms"

    if @dog.save
      redirect_to @dog, notice: "Dog was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @dog.update(dog_params)
      redirect_to @dog, notice: "Dog was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @dog.destroy

    redirect_to dogs_url, notice: "Dog was successfully destroyed."
  end

  private
    def set_dog
      @dog = Dog.find(params[:id])
    end

    def dog_params
      params.require(:dog).permit(:name, :sex, :breed, :current_weight, :birthdate, :age)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def test
    UserMailer.with(user: @user).walk_reminder_email.deliver_now

    redirect_to root_url, success: "Twilio SMS sent!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/_form.html.erb
<%= form_with(model: dog) do |form| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
        <% dog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.text_field :sex, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :breed %>
    <%= form.text_field :breed, class: 'input' %>
  </div>

  <div class="field-label is-normal" style="text-align: left;">
    <%= form.label :current_weight %>
  </div>

  <div class="field is-horizontal">
    <div class="field-body">
      <div class="field">
        <p class="control is-expanded">
          <%= form.text_field :current_weight, class: 'input' %>
        </p>
      </div>

      <div class="field">
        <div class="control is-expanded">
          <div class="select" style="width: 100%">
            <select name="units" style="width: 100%">
              <option value="pounds">pounds</option>
              <option value="kilograms">kilograms</option>
            </select>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate, start_year: 2000, end_year: Date.today.year %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, class: 'input' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<%= javascript_pack_tag 'sauce' %>

<div class="container">
  <h1 class="dog-index-title">Dogs (REACT)</h1>

  <div id="sauceindex">REACT IS NOT WORKING</div>
</div>

<hr>

<div class="container">
  <h1 class="dog-index-title">Dogs (NON-REACT)</h1>

  <div class="dog-index-container">
    <% @dogs.each do |dog| %>
      <div class="dog-list">
        <p class="dog-show-link"><%= link_to dog.name, dog %></p>
      </div>
    <% end %>
  </div>

  <div class="new-dog">
    <%= link_to 'New Dog', new_dog_path, class: "new-dog-link" %>
  </div>
</div>

app/views/dogs/new.html.erb
<div class="container">
  <h1>New Dog</h1>

  <%= render 'form', dog: @dog %>

  <%= link_to 'Back', dogs_path %>
</div>

app/views/dogs/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @dog.name %>
  </p>

  <p>
    <strong>Sex:</strong>
    <%= @dog.sex %>
  </p>

  <p>
    <strong>Breed:</strong>
    <%= @dog.breed %>
  </p>

  <p>
    <strong>Current weight:</strong>
    <%= @dog.current_weight %>
    <%= @dog.is_metric? ? "kilograms" : "pounds" %>
  </p>

  <p>
    <strong>Birthdate:</strong>
    <%= @dog.birthdate %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= @dog.age %>
  </p>

  <%= link_to 'Edit', edit_dog_path(@dog) %>
  <%= link_to 'Destroy', @dog, class: 'dog-delete-link', method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Back', dogs_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PupHelper</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'sauce' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      PupHelper
    </h1>
    <p class="subtitle">
      My first website with <strong>Bulma</strong>!
    </p>
  </div>
</section>